"use client";

import React from "react";
import Link from "next/link";
import { ArrowRight, BrainCircuit } from "lucide-react";
import { PRIMARY_AI_SIGNAL, SECONDARY_AI_SIGNALS } from "@/lib/mock-data";

const MARKET_DIGESTS = [
  {
    id: "digest-1",
    tag: "Macro Digest",
    title: "Federal Reserve Interest Rate Expectations & Tech Multiple Expansion",
    summary:
      "Algorithmic scans show mega-cap tech stocks finding support near 50-day moving averages as bond yields stabilize. Breadth has expanded to industrials and renewable energy.",
    impact: "Positive for swing paper traders testing growth baskets.",
    date: "Today at 07:45 AM",
  },
  {
    id: "digest-2",
    tag: "Volatility Scan",
    title: "VIX Compression Signals Low Implied Volatility: Breakouts Looming",
    summary:
      "The CBOE Volatility Index slipped below 14.5. Historical modeling shows extended periods of low volatility usually precede high-momentum trend continuations.",
    impact: "Ideal time to practice breakout strategies on watchlists.",
    date: "Yesterday",
  },
  {
    id: "digest-3",
    tag: "Volume Anomaly",
    title: "Unusual Institutional Block Flow Detected in Semiconductor Segment",
    summary:
      "NVDA and AMD registered 1.4x standard 20-day volume on upticks, suggesting accumulation by algorithmic funds.",
    impact: "Focus on technical continuation patterns.",
    date: "Sep 08, 2026",
  },
];

export default function AIInsightsPage() {
  const allSignals = [PRIMARY_AI_SIGNAL, ...SECONDARY_AI_SIGNALS];

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2">
          <div className="h-7 w-7 rounded-lg bg-primary/10 flex items-center justify-center text-primary">
            <BrainCircuit className="h-4 w-4" />
          </div>
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            AI Market Insights & Pattern Scans
          </h2>
        </div>
        <p className="text-xs text-muted-foreground mt-1">
          Automated algorithmic pattern recognition translated into plain English for paper traders
        </p>
      </div>

      {/* Featured AI Digest Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {MARKET_DIGESTS.map((digest) => (
          <div key={digest.id} className="fintech-card p-5 space-y-3">
            <div className="flex items-center justify-between">
              <span className="rounded bg-primary/10 px-2 py-0.5 text-[10px] font-bold text-primary uppercase">
                {digest.tag}
              </span>
              <span className="text-[10px] text-muted-foreground">{digest.date}</span>
            </div>

            <h3 className="font-bold text-sm text-foreground leading-snug">
              {digest.title}
            </h3>

            <p className="text-xs text-muted-foreground leading-relaxed">
              {digest.summary}
            </p>

            <div className="p-2.5 rounded-lg bg-muted/40 text-[11px] space-y-0.5">
              <span className="font-semibold text-primary block">Paper Trader Takeaway:</span>
              <span className="text-foreground/90">{digest.impact}</span>
            </div>
          </div>
        ))}
      </div>

      {/* Active Algorithmic Signal List */}
      <div className="fintech-card p-5 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-bold text-base text-foreground">
              Active Indicator Setups Detected
            </h3>
            <span className="text-xs text-muted-foreground">
              Educational setup directory generated by statistical scans
            </span>
          </div>
          <Link
            href="/learn/signals"
            className="text-xs font-semibold text-primary hover:underline flex items-center gap-1"
          >
            <span>Indicator Guide</span>
            <ArrowRight className="h-3 w-3" />
          </Link>
        </div>

        <div className="space-y-3">
          {allSignals.map((signal) => (
            <div
              key={signal.id}
              className="p-4 rounded-xl border border-border bg-card/60 space-y-2 hover:border-primary/40 transition-colors"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2.5">
                  <span className="font-bold text-base text-foreground">
                    {signal.symbol}
                  </span>
                  <span className="text-xs text-muted-foreground font-medium">
                    {signal.name}
                  </span>
                  <span className="rounded bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-[10px] font-bold px-2 py-0.5 uppercase">
                    {signal.type}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-muted-foreground">Confidence:</span>
                  <span className="text-xs font-bold text-foreground">
                    {signal.confidence}% High
                  </span>
                </div>
              </div>

              <h4 className="font-semibold text-sm text-foreground">
                {signal.title} · {signal.timeframe}
              </h4>

              <p className="text-xs text-muted-foreground leading-relaxed">
                {signal.summary}
              </p>

              <div className="flex items-center justify-between pt-2 border-t border-border/40 text-xs">
                <span className="text-muted-foreground text-[11px]">
                  Suggested Target: {signal.suggestedAction}
                </span>
                <Link
                  href={`/trade?symbol=${signal.symbol}`}
                  className="font-semibold text-primary hover:underline flex items-center gap-1"
                >
                  <span>Simulate Setup</span>
                  <ArrowRight className="h-3 w-3" />
                </Link>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
